### ISSUE TITLE
Optional style request : Verified & Moderator

### ISSUE THREAD

**Issue by LianhuanJ** [lekoOwO/SuperChat-Generator#1]
SVG file NOT support to be uploaded here, data_url offered below 

### Verified
`data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" version="1.1" id="Layer_1" viewBox="0 0 16 16" enable-background="new 0 0 16 16" xml:space="preserve" height="16px" width="16px" fill="rgb(153,153,153)"><g transform="scale(0.66)"><path d="M9 16.2L4.8 12l-1.4 1.4L9 19 21 7l-1.4-1.4L9 16.2z" /></g></svg>`

### Moderator
`data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" version="1.1" id="Layer_1" viewBox="0 0 16 16" enable-background="new 0 0 16 16" xml:space="preserve" height="16px" width="16px" fill="rgb(94,132,241)">
<path d="M9.64589146,7.05569719 C9.83346524,6.562372 9.93617022,6.02722257 9.93617022,5.46808511 C9.93617022,3.00042984 7.93574038,1 5.46808511,1 C4.90894765,1 4.37379823,1.10270499 3.88047304,1.29027875 L6.95744681,4.36725249 L4.36725255,6.95744681 L1.29027875,3.88047305 C1.10270498,4.37379824 1,4.90894766 1,5.46808511 C1,7.93574038 3.00042984,9.93617022 5.46808511,9.93617022 C6.02722256,9.93617022 6.56237198,9.83346524 7.05569716,9.64589147 L12.4098057,15 L15,12.4098057 L9.64589146,7.05569719 Z" /></svg>`

**Comment by lekoOwO** [comment]
It'll be great if you can provide more info like the color set and the distance between icon and titles... etc
A example picture will also be really helpful.

**Comment by LianhuanJ** [comment]
> It'll be great if you can provide more info like the color set and the distance between icon and titles... etc
> A example picture will also be really helpful.

Dear my friend, the **colors** are in the code, and there is **no distance** between icons by default,
and the **title** of each icon is as same as its title.

And if you think the example picture will really be really helpful, here they are.

![verified](https://user-images.githubusercontent.com/44343440/101673620-60e21e80-3a92-11eb-8eff-1724d0f61660.png)

![moderator](https://user-images.githubusercontent.com/44343440/101674055-f7aedb00-3a92-11eb-808a-bb4421b4b26d.png)

**Comment by lekoOwO** [comment]
nah i mean the sc screenshot since I dont get one w/ these icons

**Comment by LianhuanJ** [comment]
Hadn't expected you were asking for that kinda things, I felt so sorry about that, my bad.

Here is the screenshot, watch out  your back, there might be some kinda copyright attack
![image](https://user-images.githubusercontent.com/44343440/101677466-92a9b400-3a97-11eb-9261-5f1330d749f5.png)

**Comment by lekoOwO** [comment]
hmmm this is a chat comment, not a sc.

**Comment by lekoOwO** [comment]
i could do a comment generator though, it might be more easier than a sc since there are no stoopid varying color sets

**Comment by jim60105** [comment]
FYI, the style of mod SC is the same as other accounts.
https://youtu.be/fNBT5xLIA2s?t=670  (mind the volume)
![2021-07-21 21 35 15](https://user-images.githubusercontent.com/16995691/126497569-d6b08d39-bf15-48d7-9f62-92259a469e60.png)
![2021-07-21 21 34 54](https://user-images.githubusercontent.com/16995691/126497572-7d3c3561-5a32-41d7-9970-d56c00675b91.png)

Also, no ticks on verified channels.
https://youtu.be/lDP6sDsUa4A?t=8076  (mind the volume too)
![2021-07-21 21 41 32](https://user-images.githubusercontent.com/16995691/126498588-4bb10e6c-418d-4abe-86f0-7c62af9d4450.png)

**Comment by lekoOwO** [comment]
> FYI, the style of mod SC is the same as other accounts.
> https://youtu.be/fNBT5xLIA2s?t=670 (mind the volume)
> ![2021-07-21 21 35 15](https://user-images.githubusercontent.com/16995691/126497569-d6b08d39-bf15-48d7-9f62-92259a469e60.png)
> ![2021-07-21 21 34 54](https://user-images.githubusercontent.com/16995691/126497572-7d3c3561-5a32-41d7-9970-d56c00675b91.png)
> 
> Also, no ticks on verified channels.
> https://youtu.be/lDP6sDsUa4A?t=8076 (mind the volume too)
> ![2021-07-21 21 41 32](https://user-images.githubusercontent.com/16995691/126498588-4bb10e6c-418d-4abe-86f0-7c62af9d4450.png)

Good point. I'll close the issue then.
